export const GENDERS = [
    "Male",
    "Female",
    "Non-Binary",
    "Other",
    "Prefer not to say"
  ];

export const CITIES = [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Barcelona",
    "Lazio",
    "Trieste",
    "Venice",
    "Verona",
    "Brescia",
    "Parma",
    "Modena",
    "Reggio Emilia",
    "Perugia",
    "Trento",
    "Pisa",
    "Ancona",
    "L'Aquila",
    "Other",
  ];

  export const JOBS = [
    "Accountant",
    "Actor",
    "Actuary",
    "Anesthesiologist",
    "Arborist",
    "Architect",
    "Art Director",
    "Artist",
    "Athletic Trainer",
    "Auditor",
    "Author",
    "Baker",
    "Banker",
    "Barber",
    "Bartender",
    "Biologist",
    "Broadcaster",
    "Building Inspector",
    "Business Manager",
    "Carpenter",
    "Chef",
    "Chemist",
    "Chiropractor",
    "Civil Engineer",
    "Coast Guard",
    "Computer Programmer",
    "Conservation Scientist",
    "Construction Worker",
    "Counselor",
    "Dentist",
    "Designer",
    "Detective",
    "Dietitian",
    "Doctor",
    "Economist",
    "Electrician",
    "Engineer",
    "Environmental Scientist",
    "Farmer",
    "Financial Analyst",
    "Firefighter",
    "Gardener",
    "Genealogist",
    "Geologist",
    "Graphic Designer",
    "Hairstylist",
    "Historian",
    "Hotel Manager",
    "Interior Designer",
    "Jeweler",
    "Journalist",
    "Lawyer",
    "Librarian",
    "Locksmith",
    "Mechanic",
    "Medical Assistant",
    "Medical Laboratory Technician",
    "Military",
    "Musician",
    "Nurse",
    "Nutritionist",
    "Optician",
    "Optometrist",
    "Paralegal",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Physician",
    "Physicist",
    "Plumber",
    "Podiatrist",
    "Police Officer",
    "Political Scientist",
    "Psychologist",
    "Public Relations Specialist",
    "Real Estate Agent",
    "Recreation Worker",
    "Registered Nurse",
    "Reporter",
    "Respiratory Therapist",
    "Sales Representative",
    "Scientist",
    "Social Worker",
    "Sociologist",
    "Software Developer",
    "Surgeon",
    "Teacher",
    "Technical Writer",
    "Veterinarian",
    "Web Developer",
    "Writer",
    "Other",
  ];

